#!/bin/bash
#SBATCH -Jgpuexample
#SBATCH -N1 --gres=gpu:1                       # Number of nodes and GPUs required
#SBATCH --mem-per-gpu=12G                           # Memory per gpu
#SBATCH -t15                                        # Duration of the job (Ex: 15 mins)
#SBATCH -oReport-%j.out                             # Combined output and error messages file
#SBATCH --mail-type=FAIL                  # Mail preferences
#SBATCH --mail-user=jvarma3@gatech.edu            # e-mail address for notifications

module load tensorflow
python car_model.py
